<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Deve.Common.csproj" />
    <ProjectReference Include="..\..\Extra\Cache.Memory\Deve.Cache.Memory.csproj" />
    <ProjectReference Include="..\..\Extra\Cache.Redis\Deve.Cache.Redis.csproj" />
  </ItemGroup>

</Project>
