<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Deve.Diagnostics</RootNamespace>

    <UseMaui>true</UseMaui>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" />
    <PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" />
    <PackageReference Include="OpenTelemetry.Exporter.Zipkin" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Deve.Common.csproj" />
    <ProjectReference Include="..\Diagnostics.OpenTelemetry\Deve.Diagnostics.OpenTelemetry.csproj" />
  </ItemGroup>

</Project>
