<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Api\Deve.Api.csproj" />
    <ProjectReference Include="..\..\Common.Api\Deve.Common.Api.csproj" />
    <ProjectReference Include="..\Common\Deve.Tests.Common.csproj" />
  </ItemGroup>

</Project>
