//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deve.ClientApp.Maui.Resources.Strings; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class AppResources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal AppResources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deve.ClientApp.Maui.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Address.
    /// </summary>
    internal static string Address {
        get {
            return ResourceManager.GetString("Address", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cities.
    /// </summary>
    internal static string Cities {
        get {
            return ResourceManager.GetString("Cities", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Client.
    /// </summary>
    internal static string Client {
        get {
            return ResourceManager.GetString("Client", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Clients.
    /// </summary>
    internal static string Clients {
        get {
            return ResourceManager.GetString("Clients", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Countries.
    /// </summary>
    internal static string Countries {
        get {
            return ResourceManager.GetString("Countries", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Identification.
    /// </summary>
    internal static string Identification {
        get {
            return ResourceManager.GetString("Identification", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Login.
    /// </summary>
    internal static string Login {
        get {
            return ResourceManager.GetString("Login", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Logout.
    /// </summary>
    internal static string Logout {
        get {
            return ResourceManager.GetString("Logout", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Username and password are required.
    /// </summary>
    internal static string MissingUsernamePassword {
        get {
            return ResourceManager.GetString("MissingUsernamePassword", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Name.
    /// </summary>
    internal static string Name {
        get {
            return ResourceManager.GetString("Name", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Password.
    /// </summary>
    internal static string Password {
        get {
            return ResourceManager.GetString("Password", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to States.
    /// </summary>
    internal static string States {
        get {
            return ResourceManager.GetString("States", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Tax Id.
    /// </summary>
    internal static string TaxId {
        get {
            return ResourceManager.GetString("TaxId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Tax Name.
    /// </summary>
    internal static string TaxName {
        get {
            return ResourceManager.GetString("TaxName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Trade Name.
    /// </summary>
    internal static string TradeName {
        get {
            return ResourceManager.GetString("TradeName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Username.
    /// </summary>
    internal static string Username {
        get {
            return ResourceManager.GetString("Username", resourceCulture);
        }
    }
}
