<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Api\Deve.Api.csproj" />
    <ProjectReference Include="..\..\Sdk\Deve.Sdk.csproj" />
    <ProjectReference Include="..\Api\Deve.Tests.Api.csproj" />
    <ProjectReference Include="..\Common\Deve.Tests.Common.csproj" />
  </ItemGroup>

</Project>
