name: deve-prod
services:
  api-internal:
    image: ${ACR_LOGIN_SERVER}/api-internal:${IMAGE_TAG}
    container_name: prod-api-internal
    expose:
      - "80"
      - "443"
    ports:
      - "8081:80"
      - "444:443"
  
  api-external:
    image: ${ACR_LOGIN_SERVER}/api-external:${IMAGE_TAG}
    container_name: prod-api-external
    expose:
      - "443"
    ports:
      - "8080:80"
      - "443:443"

  cache-redis:
    container_name: prod-cache-redis

  prometheus:
    image: ${ACR_LOGIN_SERVER}/prometheus:${IMAGE_TAG}
    container_name: prod-prometheus

  grafana:
    image: ${ACR_LOGIN_SERVER}/grafana:${IMAGE_TAG}
    container_name: prod-grafana

  zipkin:
    container_name: prod-zipkin
