name: deve
services:
  api:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile.Api
    depends_on:
      - redis
      - prometheus
      - zipkin
      - grafana
    networks:
      - deve-network

  redis:
    image: redis:8.8.2
    expose:
      - 6379
    networks:
      - deve-network

  prometheus:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile.Prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - deve-network

  grafana:    
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile.Grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      #GF_LOG_LEVEL: debug
      GF_SECURITY_ADMIN_USER: "admin"
    depends_on:
      - prometheus
    networks:
      - deve-network

  zipkin:
    image: openzipkin/zipkin:3.6.1
    ports:
      - 9411:9411
    networks:
      - deve-network

  otel-collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.159.0
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./otel/otel-config.yaml:/etc/otel/config.yaml
    expose:
      - 4317
      - 4318
    depends_on:
      - zipkin
    networks:
      - deve-network

networks:
  deve-network:
