name: deve-prod
services:
  api-internal:
    image: ${ACR_LOGIN_SERVER}/api-internal:${IMAGE_TAG}
    container_name: prod-api-internal
    expose:
      - "443"
    ports:
      - "444:443"
    environment:
      ConnectionStrings__DataSourceConnection: "Server=localhost;Database=dbname;User Id=user;Password=pwd;"
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "https://+:443"
  
  api-external:
    image: ${ACR_LOGIN_SERVER}/api-external:${IMAGE_TAG}
    container_name: prod-api-external
    expose:
      - "443"
    ports:
      - "443:443"
    environment:
      ConnectionStrings__DataSourceConnection: "Server=localhost;Database=dbname;User Id=user;Password=pwd;"
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "https://+:443"

  cache-redis:
    container_name: prod-cache-redis

  prometheus:
    image: ${ACR_LOGIN_SERVER}/prometheus:${IMAGE_TAG}
    container_name: prod-prometheus

  grafana:
    image: ${ACR_LOGIN_SERVER}/grafana:${IMAGE_TAG}
    container_name: prod-grafana

  zipkin:
    container_name: prod-zipkin
