name: deve-prod
services:
  api-internal:
    container_name: prod-api-internal
    expose:
      - "443"
    ports:
      - "444:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "https://+:443"
  
  api-external:
    container_name: prod-api-external
    expose:
      - "443"
    ports:
      - "443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "https://+:443"

  cache-redis:
    container_name: prod-cache-redis

  prometheus:
    container_name: prod-prometheus

  grafana:
    container_name: prod-grafana

  zipkin:
    container_name: prod-zipkin
