name: deve-prod
services:
  api:
    image: ${ACR_LOGIN_SERVER}/api:${IMAGE_TAG}
    container_name: prod-api
    expose:
      - "8080"
    ports:
      - "8080:8080"
  
  redis:
    container_name: prod-redis

  prometheus:
    image: ${ACR_LOGIN_SERVER}/prometheus:${IMAGE_TAG}
    container_name: prod-prometheus

  grafana:
    image: ${ACR_LOGIN_SERVER}/grafana:${IMAGE_TAG}
    container_name: prod-grafana

  zipkin:
    container_name: prod-zipkin
