name: deve-dev
services:
  api:
    container_name: api
    ports:
      - "8081:80"
      - "7245:443"
    environment:
      ConnectionStrings__YourModuleConnectionRead: "Server=localhost;Database=dbname;User Id=user;Password=pwd;"
      ConnectionStrings__YourModuleConnectionWrite: "Server=localhost;Database=dbname;User Id=user;Password=pwd;"
      ConnectionStrings__RedisCacheConnection: "redis:6379"
      AppSettings__JwtKeys__SigningSecretKey: "11223344556677889900AABBCCDDEEFF"
      AppSettings__JwtKeys__EncryptionSecretKey: "FFEEDDCCBBAA00998877665544332211"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80;https://+:443"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Devel-Cert-Only"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/dev_cert.pfx"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
      OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_SERVICE_NAME: "api"
      OTEL_RESOURCE_ATTRIBUTES: "service.instance.id=$(uuidgen)"
      PROMETHEUS_SCRAPE_ENDPOINT: "/metrics"
      #APPLICATIONINSIGHTS_CONNECTION_STRING: ""
    volumes:
      - ./https:/https:ro

  redis:
    container_name: redis

  prometheus:
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.dev.yml'
      - '--web.enable-otlp-receiver'

  grafana:
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "grafana"

  zipkin:
    container_name: zipkin

  otel-collector:
    container_name: otel-collector
