# Build
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
COPY . /src
RUN dotnet restore /src/Deve.Api.Internal.sln
RUN dotnet publish /src/Internal/Api/Deve.Internal.Api.csproj -c Release -o /app --no-restore

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
COPY --from=build /app /app
ENTRYPOINT ["dotnet", "/app/Deve.Internal.Api.dll"]
