<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Deve.Diagnostics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sentry" Version="6.4.1" />
    <PackageReference Include="Sentry.OpenTelemetry" Version="6.4.1" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry" Version="1.15.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Deve.Common.csproj" />
  </ItemGroup>

</Project>
