<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Deve.Diagnostics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sentry" />
    <PackageReference Include="Sentry.OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Api" />
    <PackageReference Include="OpenTelemetry" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Deve.Common.csproj" />
  </ItemGroup>

</Project>
