<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Deve.Diagnostics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Exporter.Zipkin" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Process" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="OpenTelemetry.Instrumentation.StackExchangeRedis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Deve.Common.csproj" />
    <ProjectReference Include="..\Cache.Redis\Deve.Cache.Redis.csproj" />
    <ProjectReference Include="..\Diagnostics.OpenTelemetry\Deve.Diagnostics.OpenTelemetry.csproj" />
  </ItemGroup>

</Project>
