<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Clients\Maui\Deve.Clients.Maui.csproj" />
    <ProjectReference Include="..\..\Core\Deve.Core.csproj" />
    <ProjectReference Include="..\Common\Deve.Tests.Common.csproj" />
    <ProjectReference Include="..\Core\Deve.Tests.Core.csproj" />
  </ItemGroup>

</Project>
